### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by judemont** [douxxu/piwave#5]
Hi how are you ? I realy I'm searching for collabortor for a new innovative project in the blokchain area ? Are you open to collaborate with me ?

**Comment by judemont** [comment]
It's a good oportunity for you

**Comment by douxxu** [comment]
Hi. I'm going to shit I'll tell u later

**Comment by judemont** [comment]
Buy my nft please

**Comment by judemont** [comment]
😭☠️💩

**Comment by douxxu** [comment]
No sorry I'm not interested, maybe you can try piwave at home ?

**Comment by judemont** [comment]
> No sorry I'm not interested, maybe you can try piwave at home ?

I dont have home...

**Comment by judemont** [comment]
Im sleeping in the street
